name: Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: { }

env:
  CI: true

jobs:
  build-snapshot-container:
    needs: [ linux-jvm-tests ]
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build container image
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.push=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.registry=quay.io \
          -Dquarkus.container-image.group=carlosthe19916 \
          -Dquarkus.container-image.name=windup-web-next \
          -Dquarkus.container-image.tag=latest \
          -P native,ui
      - name: Save container image
        run: docker save -o windup-web-next-container-image.tar quay.io/carlosthe19916/windup-web-next:latest
      - name: Upload container image
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: windup-web-next-container-image.tar

  snapshots-container:
    needs: [ build-snapshot-container ]
    name: Snapshot container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Login to Ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load and config images
        run: |
          # Load images from .tar
          docker load -i artifacts/windup-web-next-container-image.tar
          
          # Tag images     
          docker tag quay.io/carlosthe19916/windup-web-next:latest ghcr.io/carlosthe19916/windup-web-next/windup-web-next:early-access
      - name: Push images to registry
        run: |       
          docker push ghcr.io/carlosthe19916/windup-web-next/windup-web-next:early-access
